version: '3'

services:
  mangocompanion:
    image: ghcr.io/tr7zw/mango-companion:release
    restart: unless-stopped
    container_name: mangocompanion
    dns:
      - 8.8.8.8
    volumes:
      - "/mango/library:/workspace/library"
      - "/mango/companionCache:/root/.cache/ms-playwright"