version: '3'

services:
  mangocompanion:
    image: ghcr.io/tr7zw/mango-companion:release
    restart: unless-stopped
    dns:
      - 8.8.8.8
    volumes:
      - "/path/to/mango/library:/workspace/library"